name: model_repo

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
    flutter_lints: ^4.0.0

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^2.29.0
    cloud_firestore: ^4.16.1
    firebase_auth: ^4.19.1

